# Vaciar campos de auditoria y campos de registros de cambios.
# v1.0

# SELECCIONAR LA BASE DE DATOS DE CONFIGURACION
USE SUCONFIG;

TRUNCATE DPAUDELIMODCNF;
TRUNCATE DPAUDELIMODDIC;
TRUNCATE DPAUDITORIA;
TRUNCATE DPFILEAPLICA;
TRUNCATE DPFILES;
TRUNCATE DPINTREF;