SET @DB_DPCONFIG = 'APCONFIG', @DB_DPEMPRESA = 'APBASE';


USE APCONFIG;


INSERT INTO DPDATACNF 
(DAT_NAME, DAT_GROUP, DAT_VALUE, DAT_TYPE, DAT_MODE, DAT_LEN, DAT_FECHA,DAT_HORA) 
VALUES 
('RECONVERSION', 'DPCONFIGCHK', 'EJECUTADO', 'C', 'ALL', '1', CURRENT_DATE,CURRENT_TIME);


INSERT INTO @DB_CONFIG.dpdatacnf 
(DAT_NAME, DAT_GROUP, DAT_VALUE, DAT_TYPE, DAT_MODE, DAT_LEN, DAT_FECHA,DAT_HORA) 
VALUES 
('RECONVERSION', 'DPCONFIGCHK', 'EJECUTADO', 'C', 'ALL', '1', CURRENT_DATE,CURRENT_TIME);

DROP FUNCTION IF EXISTS HOLAMUNDO;

DELIMITER //

CREATE FUNCTION HOLAMUNDO() RETURNS VARCHAR(20)
BEGIN
    RETURN 'HolaMundo';
END
//



SELECT HOLAMUNDO();





USE APCONFIG;



SELECT SUM(DAT_LEN) 
FROM DPDATACNF
WHERE DAT_NAME='RECONVERSION' ; 










