# Reconversion de datos valorizados (montos), dividos entre 1 millon y redondeados a 2 decimales.
# v3.0

# SELECCIONAR LA BASE DE DATOS DE LA EMPRESA
USE ERP_RECONVERSION;

# NO ALTERAR FORMULAS DEBAJO DE ESTA LINEA
# ==============================================

# MONTO DE LA DIVISION
SET @RECONVERSION=1000000;


UPDATE NMACUMCON SET
ACU_01=ROUND((ACU_01/@RECONVERSION),2),
ACU_02=ROUND((ACU_02/@RECONVERSION),2),
ACU_03=ROUND((ACU_03/@RECONVERSION),2),
ACU_04=ROUND((ACU_04/@RECONVERSION),2),
ACU_05=ROUND((ACU_05/@RECONVERSION),2),
ACU_06=ROUND((ACU_06/@RECONVERSION),2),
ACU_07=ROUND((ACU_07/@RECONVERSION),2),
ACU_08=ROUND((ACU_08/@RECONVERSION),2),
ACU_09=ROUND((ACU_09/@RECONVERSION),2),
ACU_10=ROUND((ACU_10/@RECONVERSION),2),
ACU_11=ROUND((ACU_11/@RECONVERSION),2),
ACU_12=ROUND((ACU_12/@RECONVERSION),2);

UPDATE NMARI SET
ARI_INGANU=ROUND((ARI_INGANU/@RECONVERSION),2),
ARI_INSDOC=ROUND((ARI_INSDOC/@RECONVERSION),2),
ARI_HCM=ROUND((ARI_HCM/@RECONVERSION),2),
ARI_SERMED=ROUND((ARI_SERMED/@RECONVERSION),2),
ARI_ALQUIL=ROUND((ARI_ALQUIL/@RECONVERSION),2),
ARI_OTRING=ROUND((ARI_OTRING/@RECONVERSION),2),
ARI_IMPMAS=ROUND((ARI_IMPMAS/@RECONVERSION),2),
ARI_A=ROUND((ARI_A/@RECONVERSION),2),
ARI_B=ROUND((ARI_B/@RECONVERSION),2),
ARI_C=ROUND((ARI_C/@RECONVERSION),2),
ARI_D=ROUND((ARI_D/@RECONVERSION),2),
ARI_F=ROUND((ARI_F/@RECONVERSION),2),
ARI_G=ROUND((ARI_G/@RECONVERSION),2),
ARI_H=ROUND((ARI_H/@RECONVERSION),2),
ARI_I=ROUND((ARI_I/@RECONVERSION),2),
ARI_J=ROUND((ARI_J/@RECONVERSION),2),
ARI_K=ROUND((ARI_K/@RECONVERSION),2),
ARI_ISLR=ROUND((ARI_ISLR/@RECONVERSION),2),
ARI_ASIGNA=ROUND((ARI_ASIGNA/@RECONVERSION),2),
ARI_H1=ROUND((ARI_H1/@RECONVERSION),2),
ARI_H2=ROUND((ARI_H2/@RECONVERSION),2),
ARI_H3=ROUND((ARI_H3/@RECONVERSION),2),
ARI_UT=ROUND((ARI_UT/@RECONVERSION),2);

UPDATE NMASIENTOS SET 
ASI_MONTO=ROUND((ASI_MONTO/@RECONVERSION),2);

UPDATE NMCARGOS	SET 
CAR_SUELDO=ROUND((CAR_SUELDO/@RECONVERSION),2);

UPDATE NMCOMPHCMPER	SET 
PHC_MONTO=ROUND((PHC_MONTO/@RECONVERSION),2),
PHC_EXONER=ROUND((PHC_EXONER/@RECONVERSION),2);
						
UPDATE NMCUOTASGUARD SET 
CMG_MTOAPL=ROUND((CMG_MTOAPL/@RECONVERSION),2),
CMG_MONTO=ROUND((CMG_MONTO/@RECONVERSION),2);
						
UPDATE NMCURRICULUM	SET 
CUR_SUELDO=ROUND((CUR_SUELDO/@RECONVERSION),2);

UPDATE NMEXPEDIENTE	SET 
EXP_MONTO=ROUND((EXP_MONTO/@RECONVERSION),2);

UPDATE NMEXPLABORAL	SET 
ELB_SUELDO=ROUND((ELB_SUELDO/@RECONVERSION),2);

UPDATE NMFCHPRESTM	SET 
FDP_CUOTA=ROUND((FDP_CUOTA/@RECONVERSION),2);

UPDATE NMHCM SET 
HCM_MONTO=ROUND((HCM_MONTO/@RECONVERSION),2);

UPDATE NMHCMCUOTAS SET 
CHC_CUOTA=ROUND((CHC_CUOTA/@RECONVERSION),2),
CHC_CAPITA=ROUND((CHC_CAPITA/@RECONVERSION),2),
CHC_INTERE=ROUND((CHC_INTERE/@RECONVERSION),2);
						
UPDATE NMHCMFAMCUOTAS SET 
HCF_CUOTA=ROUND((HCF_CUOTA/@RECONVERSION),2),
HCF_CAPITA=ROUND((HCF_CAPITA/@RECONVERSION),2),
HCF_INTERE=ROUND((HCF_INTERE/@RECONVERSION),2);
						
UPDATE NMHCMFAMILIA	SET 
HFM_MONTO=ROUND((HFM_MONTO/@RECONVERSION),2),
HFM_EXONER=ROUND((HFM_EXONER/@RECONVERSION),2);
						
UPDATE NMHISTORICO SET 
HIS_MONTO=ROUND((HIS_MONTO/@RECONVERSION),2);
/*HIS_VARIAC=ROUND((HIS_VARIAC/@RECONVERSION),2);*/						
						
UPDATE NMHTTPINTERES SET 
INT_INTERE=ROUND((INT_INTERE/@RECONVERSION),2),
INT_CAPITA=ROUND((INT_CAPITA/@RECONVERSION),2),
INT_ABONO=ROUND((INT_ABONO/@RECONVERSION),2);						

UPDATE NMOBSERV	SET 
OBS_FACTO1=ROUND((OBS_FACTO1/@RECONVERSION),2),
OBS_FACTO2=ROUND((OBS_FACTO2/@RECONVERSION),2),
OBS_FACTO3=ROUND((OBS_FACTO3/@RECONVERSION),2),
OBS_FACTO4=ROUND((OBS_FACTO4/@RECONVERSION),2);

UPDATE NMPRENOMINA SET 
HIS_MONTO=ROUND((HIS_MONTO/@RECONVERSION),2),
HIS_FACTO2=ROUND((HIS_FACTO2/@RECONVERSION),2),
HIS_FACTO1=ROUND((HIS_FACTO1/@RECONVERSION),2),
HIS_FACTO3=ROUND((HIS_FACTO3/@RECONVERSION),2),
HIS_FACTO4=ROUND((HIS_FACTO4/@RECONVERSION),2);	
/*HIS_VARIAC=ROUND((HIS_VARIAC/@RECONVERSION),3),*/
						
UPDATE NMRESTRA	SET 
RMT_PROM_A=ROUND((RMT_PROM_A/@RECONVERSION),2),
RMT_PROM_B=ROUND((RMT_PROM_B/@RECONVERSION),2),
RMT_PROM_C=ROUND((RMT_PROM_C/@RECONVERSION),2),
RMT_ASIGNA=ROUND((RMT_ASIGNA/@RECONVERSION),2),
RMT_DEDUCC=ROUND((RMT_DEDUCC/@RECONVERSION),2),
RMT_PROM_D=ROUND((RMT_PROM_D/@RECONVERSION),0),
RMT_SUELDO=ROUND((RMT_SUELDO/@RECONVERSION),2);
					
UPDATE NMTABPRES SET 
PRE_MONTO=ROUND((PRE_MONTO/@RECONVERSION),2),
PRE_CUOTA=ROUND((PRE_CUOTA/@RECONVERSION),2),
PRE_INTERE=ROUND((PRE_INTERE/@RECONVERSION),2);
						
UPDATE NMTABVACVEN SET 
PRE_MONTO=ROUND((PRE_MONTO/@RECONVERSION),2),
PRE_CUOTA=ROUND((PRE_CUOTA/@RECONVERSION),2),
PRE_TASA=ROUND((PRE_TASA/@RECONVERSION),2),
PRE_INTERE=ROUND((PRE_INTERE/@RECONVERSION),2);

UPDATE NMTRABAJADOR SET 
RET_HCM=ROUND((RET_HCM/@RECONVERSION),2),
CAJA_AHORR=ROUND((CAJA_AHORR/@RECONVERSION),2),
SINDICATO=ROUND((SINDICATO/@RECONVERSION),2),
VEHICULO=ROUND((VEHICULO/@RECONVERSION),2),
SALARIO=ROUND((SALARIO/@RECONVERSION),2),
PORC_COMI=ROUND((PORC_COMI/@RECONVERSION),2),
PENSION_AL=ROUND((PENSION_AL/@RECONVERSION),2),
CAJ_APORTE=ROUND((CAJ_APORTE/@RECONVERSION),2),
RESERVADO1=ROUND((RESERVADO1/@RECONVERSION),2),
RESERVADO2=ROUND((RESERVADO2/@RECONVERSION),2);

UPDATE NMTRABGUARD SET	
GXT_MONTO=ROUND((GXT_MONTO/@RECONVERSION),2),
GXT_MTOINS=ROUND((GXT_MTOINS/@RECONVERSION),2);

UPDATE NMVARHTTP SET 
VAR_CANTID=ROUND((VAR_CANTID/@RECONVERSION),3);						

/*UPDATE NMVARIAC	SET	
VAR_AJUSTE=ROUND((VAR_AJUSTE/@RECONVERSION),3),
VAR_CANTID=ROUND((VAR_CANTID/@RECONVERSION),3);*/

TRUNCATE NMAUDITORIA;
